[package]
name = "paste-anywhere"
version = "0.1.0"
authors = ["Markus Richter", "Leo Balduf"]

[dependencies]
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.7"
rand = "0.4"
byteorder = "1"