[package]
name = "paste-anywhere"
version = "0.1.0"
authors = ["Markus Richter", "Leo Balduf"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"

# serde_json is just for the example, not required in general
serde_json = "1.0"

vectorclock-rs = "*"